// AUTO-GENERATED by scripts/emit-portfolio-data.mjs — DO NOT EDIT BY HAND.
// Source of truth: DPMC portfolio-projects/projects-master.json
import type { DTIProject } from "./portfolio-types";

export const DTI_PROJECTS: DTIProject[] = [
  {
    "id": "bw181a",
    "contractNumber": "BW181A 892 A24",
    "projectCode": "BW181A",
    "fiscalYear": 2026,
    "contractor": "JE Wilson Ventilation Ltd",
    "contractorLocation": "Saint John NB",
    "trade": "HVAC & Ventilation",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-12-19",
      "awarded": "2026-01-26",
      "startup": "2026-02-20",
      "substantial": "",
      "final": ""
    },
    "status": "Active",
    "facilityName": "Provincial Facility HVAC Upgrade",
    "region": "New Brunswick",
    "scope": "Ventilation and HVAC system replacement for a Government of New Brunswick building, including equipment procurement lead-time management and seasonal changeover planning.",
    "highlights": [
      "Tendered and awarded through the winter season (issued December 2025, awarded January 2026) with February mobilization",
      "Open public tender awarded to a Saint John ventilation specialist",
      "Currently active under construction management"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/13-warehouse-industrial.jpg"
  },
  {
    "id": "bw186a",
    "contractNumber": "BW186A 877 A24",
    "projectCode": "BW186A",
    "fiscalYear": 2026,
    "contractor": "East Coast Sheet Metal Ltd",
    "contractorLocation": "Dieppe NB",
    "trade": "HVAC & Ventilation",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-11-27",
      "awarded": "2026-01-30",
      "startup": "2026-02-25",
      "substantial": "",
      "final": ""
    },
    "status": "Active",
    "facilityName": "Provincial Facility HVAC Upgrade",
    "region": "New Brunswick",
    "scope": "Ventilation and HVAC system replacement for a Government of New Brunswick building, including equipment procurement lead-time management and seasonal changeover planning.",
    "highlights": [
      "Winter tender cycle — issued November 2025, awarded January 2026, on site by late February",
      "Open public tender awarded to a Dieppe sheet-metal contractor",
      "Currently active under construction management"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/03-glass-tower.jpg"
  },
  {
    "id": "bw5109",
    "contractNumber": "BW5109 888 A24",
    "projectCode": "BW5109",
    "fiscalYear": 2025,
    "contractor": "Bellebay Construction Inc",
    "contractorLocation": "Bloomfield Kings Co NB",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-02-11",
      "awarded": "2025-03-24",
      "startup": "2025-04-10",
      "substantial": "2025-09-02",
      "final": "2025-10-22"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Renovation",
    "region": "New Brunswick",
    "scope": "General construction and interior renovation of a Government of New Brunswick facility, coordinating multiple sub-trades from tender through substantial completion.",
    "highlights": [
      "Delivered within a single construction season — April startup to September substantial completion",
      "Managed from open tender (February 2025) through final completion in October 2025"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/01-construction-site.jpg"
  },
  {
    "id": "bw5110",
    "contractNumber": "BW5110 768 A24",
    "projectCode": "BW5110",
    "fiscalYear": 2025,
    "contractor": "Jones and Oak Contracting (13691977 Canada Inc)",
    "contractorLocation": "Killarney Road NB",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2026-02-19",
      "awarded": "2026-03-17",
      "startup": "",
      "substantial": "",
      "final": ""
    },
    "status": "Active",
    "facilityName": "Provincial Facility Renovation",
    "region": "New Brunswick",
    "scope": "General construction and interior renovation of a Government of New Brunswick facility, coordinating multiple sub-trades from tender through substantial completion.",
    "highlights": [
      "Fast tender-to-award turnaround — under four weeks from tender issue to contract award",
      "Currently active under construction management"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/02-building-crane.jpg"
  },
  {
    "id": "bw5175",
    "contractNumber": "BW5175 787 A24",
    "projectCode": "BW5175",
    "fiscalYear": 2025,
    "contractor": "King Construction Limited",
    "contractorLocation": "Hanwell NB",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-05-20",
      "awarded": "2025-06-25",
      "startup": "2025-07-11",
      "substantial": "2025-11-10",
      "final": "2025-11-27"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Renovation",
    "region": "New Brunswick",
    "scope": "General construction and interior renovation of a Government of New Brunswick facility, coordinating multiple sub-trades from tender through substantial completion.",
    "highlights": [
      "Completed within one construction season — July startup to November substantial completion",
      "Closed out quickly, reaching final completion 17 days after substantial",
      "One of two concurrent contracts managed with the same Hanwell contractor in FY2025"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/05-concrete-building.jpg"
  },
  {
    "id": "bw5187",
    "contractNumber": "BW5187 SH9 A24",
    "projectCode": "BW5187",
    "fiscalYear": 2025,
    "contractor": "Eclipse Construction Services Ltd",
    "contractorLocation": "Rothesay NB",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-06-11",
      "awarded": "2025-07-10",
      "startup": "2025-07-24",
      "substantial": "2025-11-12",
      "final": "2025-11-27"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Renovation",
    "region": "New Brunswick",
    "scope": "General construction and interior renovation of a Government of New Brunswick facility, coordinating multiple sub-trades from tender through substantial completion.",
    "highlights": [
      "29-day tender-to-award turnaround with startup two weeks later",
      "Substantial completion in November 2025 with final completion 15 days after",
      "Repeat contractor relationship — one of multiple DTI contracts managed with this Rothesay firm"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/17-construction-workers.jpg"
  },
  {
    "id": "bw5203",
    "contractNumber": "BW5203 761 A24",
    "projectCode": "BW5203",
    "fiscalYear": 2025,
    "contractor": "Atlantic Roofers Ltd",
    "contractorLocation": "Moncton NB",
    "trade": "Roofing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-03-11",
      "awarded": "2025-04-11",
      "startup": "2025-05-02",
      "substantial": "",
      "final": ""
    },
    "status": "Active",
    "facilityName": "Provincial Facility Roof Replacement",
    "region": "New Brunswick",
    "scope": "Full roof system replacement on an occupied Government of New Brunswick facility — tear-off, insulation, membrane installation, and flashing details, coordinated to maintain building operations throughout.",
    "highlights": [
      "Awarded via open tender in April 2025 with early-May mobilization to capture the full roofing season",
      "Currently active under construction management"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/10-architectural-detail.jpg"
  },
  {
    "id": "bw5219",
    "contractNumber": "BW5219 785 A24",
    "projectCode": "BW5219",
    "fiscalYear": 2025,
    "contractor": "Dowd Roofing Inc",
    "contractorLocation": "Saint John NB",
    "trade": "Roofing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-03-26",
      "awarded": "2025-05-06",
      "startup": "2025-05-22",
      "substantial": "2025-11-24",
      "final": "2025-11-24"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Roof Replacement",
    "region": "New Brunswick",
    "scope": "Full roof system replacement on an occupied Government of New Brunswick facility — tear-off, insulation, membrane installation, and flashing details, coordinated to maintain building operations throughout.",
    "highlights": [
      "Full-season roofing program — May 2025 startup through November substantial and final completion",
      "Repeat contractor relationship — one of several DTI roofing contracts managed with this Saint John firm"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/12-bridge-structure.jpg"
  },
  {
    "id": "bw5233",
    "contractNumber": "BW5233 SH9 A24",
    "projectCode": "BW5233",
    "fiscalYear": 2025,
    "contractor": "Dowd Roofing Inc",
    "contractorLocation": "Saint John NB",
    "trade": "Roofing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-06-04",
      "awarded": "2025-06-26",
      "startup": "2025-07-11",
      "substantial": "2026-02-13",
      "final": ""
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Roof Replacement",
    "region": "New Brunswick",
    "scope": "Full roof system replacement on an occupied Government of New Brunswick facility — tear-off, insulation, membrane installation, and flashing details, coordinated to maintain building operations throughout.",
    "highlights": [
      "22-day tender-to-award turnaround in June 2025",
      "Execution carried through the winter to substantial completion in February 2026",
      "Repeat contractor relationship with an established Saint John roofing firm"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/10-architectural-detail.jpg"
  },
  {
    "id": "bw5234",
    "contractNumber": "BW5234 768 A24 -02",
    "projectCode": "BW5234",
    "fiscalYear": 2025,
    "contractor": "Dowd Roofing Inc",
    "contractorLocation": "Saint John NB",
    "trade": "Roofing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-06-17",
      "awarded": "2025-06-23",
      "startup": "2025-09-16",
      "substantial": "2025-11-20",
      "final": "2025-12-31"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Roof Replacement",
    "region": "New Brunswick",
    "scope": "Full roof system replacement on an occupied Government of New Brunswick facility — tear-off, insulation, membrane installation, and flashing details, coordinated to maintain building operations throughout.",
    "highlights": [
      "Six-day tender-to-award turnaround — issued June 17, awarded June 23, 2025",
      "Substantial completion in November 2025 with final completion by year end",
      "Repeat contractor relationship with an established Saint John roofing firm"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/12-bridge-structure.jpg"
  },
  {
    "id": "bw5250",
    "contractNumber": "BW5250 768 A24",
    "projectCode": "BW5250",
    "fiscalYear": 2025,
    "contractor": "W & S General Contractors Ltd",
    "contractorLocation": "Saint John NB",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-05-29",
      "awarded": "2025-06-25",
      "startup": "2025-07-11",
      "substantial": "2025-09-29",
      "final": "2025-10-03"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Renovation",
    "region": "New Brunswick",
    "scope": "General construction and interior renovation of a Government of New Brunswick facility, coordinating multiple sub-trades from tender through substantial completion.",
    "highlights": [
      "Compressed 11-week construction window — July startup to late-September substantial completion",
      "Final completion achieved within four days of substantial — clean, fast closeout"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/01-construction-site.jpg"
  },
  {
    "id": "bw5267",
    "contractNumber": "BW5267 779 A24",
    "projectCode": "BW5267",
    "fiscalYear": 2025,
    "contractor": "Dowd Roofing Inc",
    "contractorLocation": "Saint John NB",
    "trade": "Roofing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-06-23",
      "awarded": "2025-07-22",
      "startup": "2025-07-24",
      "substantial": "2025-12-18",
      "final": "2026-01-13"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Roof Replacement",
    "region": "New Brunswick",
    "scope": "Full roof system replacement on an occupied Government of New Brunswick facility — tear-off, insulation, membrane installation, and flashing details, coordinated to maintain building operations throughout.",
    "highlights": [
      "Mobilized within two days of award — awarded July 22, on site July 24, 2025",
      "Carried through to winter substantial completion in December 2025",
      "Repeat contractor relationship with an established Saint John roofing firm"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/10-architectural-detail.jpg"
  },
  {
    "id": "bw5288",
    "contractNumber": "BW5288 877 A24",
    "projectCode": "BW5288",
    "fiscalYear": 2025,
    "contractor": "Eclipse Construction Services Ltd",
    "contractorLocation": "Rothesay NB",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-08-19",
      "awarded": "2025-09-23",
      "startup": "2025-10-03",
      "substantial": "",
      "final": ""
    },
    "status": "Active",
    "facilityName": "Provincial Facility Renovation",
    "region": "New Brunswick",
    "scope": "General construction and interior renovation of a Government of New Brunswick facility, coordinating multiple sub-trades from tender through substantial completion.",
    "highlights": [
      "Awarded September 2025 with startup inside 10 days",
      "Repeat contractor relationship — one of multiple DTI contracts managed with this Rothesay firm",
      "Currently active under construction management"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/02-building-crane.jpg"
  },
  {
    "id": "bw5290",
    "contractNumber": "BW5290 783 A24",
    "projectCode": "BW5290",
    "fiscalYear": 2025,
    "contractor": "Leroy's Heating Services Ltd",
    "contractorLocation": "Saint John NB",
    "trade": "Mechanical & Plumbing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-09-08",
      "awarded": "2025-10-03",
      "startup": "2025-10-10",
      "substantial": "",
      "final": ""
    },
    "status": "Active",
    "facilityName": "Provincial Facility Mechanical Upgrade",
    "region": "New Brunswick",
    "scope": "Mechanical and plumbing systems upgrade in an operating government facility, including phased shutdowns and commissioning coordination.",
    "highlights": [
      "Startup within one week of the October 2025 award, carrying work into the heating season",
      "Currently active under construction management"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/13-warehouse-industrial.jpg"
  },
  {
    "id": "bw5h19",
    "contractNumber": "BW5H19 834 H02",
    "projectCode": "BW5H19",
    "fiscalYear": 2025,
    "contractor": "A-Tech Roofing Ltd",
    "contractorLocation": "Dieppe NB",
    "trade": "Roofing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-09-18",
      "awarded": "2025-10-20",
      "startup": "2025-11-04",
      "substantial": "",
      "final": ""
    },
    "status": "Active",
    "facilityName": "Provincial Facility Roof Replacement",
    "region": "New Brunswick",
    "scope": "Full roof system replacement on an occupied Government of New Brunswick facility — tear-off, insulation, membrane installation, and flashing details, coordinated to maintain building operations throughout.",
    "highlights": [
      "Late-season roofing start — awarded October 2025 with November mobilization into winter conditions",
      "Currently active under construction management"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/12-bridge-structure.jpg"
  },
  {
    "id": "bw5k18",
    "contractNumber": "BW5K18 126 B02",
    "projectCode": "BW5K18",
    "fiscalYear": 2025,
    "contractor": "Atlantic Alarm & Sound Ltd",
    "contractorLocation": "Moncton NB",
    "trade": "Electrical & Security",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-02-18",
      "awarded": "2025-04-02",
      "startup": "2025-04-17",
      "substantial": "2026-03-10",
      "final": ""
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Systems Upgrade",
    "region": "New Brunswick",
    "scope": "Electrical, fire-alarm, and security systems installation in an occupied government facility, coordinated around daily operations.",
    "highlights": [
      "Eleven-month installation program — April 2025 startup to substantial completion in March 2026",
      "Repeat contractor relationship — second DTI systems contract managed with this Moncton firm"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/09-office-interior.jpg"
  },
  {
    "id": "bw5s10",
    "contractNumber": "BW5S10 H63 NH2",
    "projectCode": "BW5S10",
    "fiscalYear": 2025,
    "contractor": "Atlantic Alliance Elevators",
    "contractorLocation": "Hanwell NB",
    "trade": "Specialty & Civil",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-08-05",
      "awarded": "2025-08-29",
      "startup": "2025-09-09",
      "substantial": "",
      "final": ""
    },
    "status": "Active",
    "facilityName": "Provincial Facility Specialty Works",
    "region": "New Brunswick",
    "scope": "Specialty construction package for a Government of New Brunswick site, managed from tender award through final completion.",
    "highlights": [
      "24-day tender-to-award turnaround in August 2025",
      "Specialist elevator contractor engaged for the vertical-transportation package",
      "Currently active under construction management"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/20-recreation-center.jpg"
  },
  {
    "id": "bw5s22",
    "contractNumber": "BW5S22 H30 NH2",
    "projectCode": "BW5S22",
    "fiscalYear": 2025,
    "contractor": "Evolution Roofing Ltd",
    "contractorLocation": "Dieppe NB",
    "trade": "Roofing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-08-27",
      "awarded": "2025-09-24",
      "startup": "2025-10-08",
      "substantial": "2026-01-21",
      "final": "2026-01-28"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Roof Replacement",
    "region": "New Brunswick",
    "scope": "Full roof system replacement on an occupied Government of New Brunswick facility — tear-off, insulation, membrane installation, and flashing details, coordinated to maintain building operations throughout.",
    "highlights": [
      "Executed through fall and winter — October 2025 startup to substantial completion in January 2026",
      "Final completion achieved seven days after substantial — tight closeout",
      "28-day tender-to-award turnaround"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/10-architectural-detail.jpg"
  },
  {
    "id": "bw5t18",
    "contractNumber": "BW5T18 V91 B5D",
    "projectCode": "BW5T18",
    "fiscalYear": 2025,
    "contractor": "King Construction Limited",
    "contractorLocation": "Hanwell NB",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-03-28",
      "awarded": "2025-05-06",
      "startup": "2025-05-26",
      "substantial": "2025-11-25",
      "final": ""
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Renovation",
    "region": "New Brunswick",
    "scope": "General construction and interior renovation of a Government of New Brunswick facility, coordinating multiple sub-trades from tender through substantial completion.",
    "highlights": [
      "Six-month build — May 2025 startup to substantial completion in November 2025",
      "Repeat contractor relationship — one of two concurrent DTI contracts managed with this Hanwell firm"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/05-concrete-building.jpg"
  },
  {
    "id": "bw5t25",
    "contractNumber": "BW5T25 00B 00B",
    "projectCode": "BW5T25",
    "fiscalYear": 2025,
    "contractor": "Westower Communications Ltd",
    "contractorLocation": "Elmira ON",
    "trade": "Electrical & Security",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-03-20",
      "awarded": "2025-05-01",
      "startup": "2025-05-16",
      "substantial": "",
      "final": ""
    },
    "status": "Active",
    "facilityName": "Provincial Facility Systems Upgrade",
    "region": "New Brunswick",
    "scope": "Electrical, fire-alarm, and security systems installation in an occupied government facility, coordinated around daily operations.",
    "highlights": [
      "Specialist communications-infrastructure contractor engaged from out of province (Ontario)",
      "Awarded May 2025 with mobilization inside three weeks",
      "Currently active under construction management"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/09-office-interior.jpg"
  },
  {
    "id": "bw5w14",
    "contractNumber": "BW5W14 766 A24",
    "projectCode": "BW5W14",
    "fiscalYear": 2025,
    "contractor": "Advanced Energy Management Ltd",
    "contractorLocation": "Dartmouth NS",
    "trade": "HVAC & Ventilation",
    "tenderType": "Sole Source",
    "dates": {
      "tenderIssued": "2025-05-27",
      "awarded": "2025-06-23",
      "startup": "2025-06-23",
      "substantial": "2025-11-19",
      "final": ""
    },
    "status": "Completed",
    "facilityName": "Provincial Facility HVAC Upgrade",
    "region": "New Brunswick",
    "scope": "Ventilation and HVAC system replacement for a Government of New Brunswick building, including equipment procurement lead-time management and seasonal changeover planning.",
    "highlights": [
      "Sole-source procurement with same-day award and startup (June 23, 2025)",
      "Specialist building-controls contractor engaged from Nova Scotia",
      "Substantial completion reached in November 2025 ahead of the heating season"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/13-warehouse-industrial.jpg"
  },
  {
    "id": "bw5w50",
    "contractNumber": "BW5W50 00B 00B",
    "projectCode": "BW5W50",
    "fiscalYear": 2025,
    "contractor": "Select Mechanical Inc",
    "contractorLocation": "Saint John NB",
    "trade": "Mechanical & Plumbing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-05-30",
      "awarded": "2025-06-25",
      "startup": "2025-07-25",
      "substantial": "",
      "final": ""
    },
    "status": "Active",
    "facilityName": "Provincial Facility Mechanical Upgrade",
    "region": "New Brunswick",
    "scope": "Mechanical and plumbing systems upgrade in an operating government facility, including phased shutdowns and commissioning coordination.",
    "highlights": [
      "26-day tender-to-award turnaround in June 2025",
      "Currently active under construction management"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/03-glass-tower.jpg"
  },
  {
    "id": "bw4142",
    "contractNumber": "BW4142 864 A24",
    "projectCode": "BW4142",
    "fiscalYear": 2024,
    "contractor": "John Flood & Sons (1961) Ltd",
    "contractorLocation": "SAINT JOHN NB",
    "trade": "Mechanical & Plumbing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2024-03-12",
      "awarded": "2024-04-18",
      "startup": "2024-05-09",
      "substantial": "2024-10-16",
      "final": "2024-10-22"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Mechanical Upgrade",
    "region": "New Brunswick",
    "scope": "Mechanical and plumbing systems upgrade in an operating government facility, including phased shutdowns and commissioning coordination.",
    "highlights": [
      "Delivered May–October 2024 with final completion six days after substantial",
      "One of three contracts managed with John Flood & Sons (1961) Ltd of Saint John"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/13-warehouse-industrial.jpg"
  },
  {
    "id": "bw4156",
    "contractNumber": "BW4156 764 A24",
    "projectCode": "BW4156",
    "fiscalYear": 2024,
    "contractor": "Avondale Construction Ltd",
    "contractorLocation": "Halifax NS",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2024-04-22",
      "awarded": "2024-05-27",
      "startup": "2024-06-03",
      "substantial": "2025-08-15",
      "final": "2026-01-06"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Renovation",
    "region": "New Brunswick",
    "scope": "General construction and interior renovation of a Government of New Brunswick facility, coordinating multiple sub-trades from tender through substantial completion.",
    "highlights": [
      "Fourteen-month major construction contract — June 2024 startup to August 2025 substantial completion",
      "Interprovincial contractor coordination with Avondale Construction of Halifax, Nova Scotia",
      "Repeat contractor relationship — Avondale also delivered the Upham depot project (BW4T18)"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/17-construction-workers.jpg"
  },
  {
    "id": "bw4167",
    "contractNumber": "BW4167 888 A24",
    "projectCode": "BW4167",
    "fiscalYear": 2024,
    "contractor": "Dowd Roofing Inc",
    "contractorLocation": "Saint John NB",
    "trade": "Roofing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-04-04",
      "awarded": "2025-05-02",
      "startup": "2025-05-23",
      "substantial": "2026-02-09",
      "final": ""
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Roof Replacement",
    "region": "New Brunswick",
    "scope": "Full roof system replacement on an occupied Government of New Brunswick facility — tear-off, insulation, membrane installation, and flashing details, coordinated to maintain building operations throughout.",
    "highlights": [
      "Roofing execution carried through the 2025–26 winter to substantial completion in February 2026",
      "One of eight contracts managed with repeat roofing contractor Dowd Roofing Inc of Saint John"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/12-bridge-structure.jpg"
  },
  {
    "id": "bw4175",
    "contractNumber": "BW4175 766 A24",
    "projectCode": "BW4175",
    "fiscalYear": 2024,
    "contractor": "Dowd Roofing Inc",
    "contractorLocation": "Saint John NB",
    "trade": "Roofing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2024-03-26",
      "awarded": "2024-04-22",
      "startup": "2024-04-30",
      "substantial": "2024-11-22",
      "final": "2024-11-22"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Roof Replacement",
    "region": "New Brunswick",
    "scope": "Full roof system replacement on an occupied Government of New Brunswick facility — tear-off, insulation, membrane installation, and flashing details, coordinated to maintain building operations throughout.",
    "highlights": [
      "Full-season roof replacement April–November 2024, with substantial and final completion the same day",
      "One of eight contracts managed with repeat roofing contractor Dowd Roofing Inc of Saint John"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/10-architectural-detail.jpg"
  },
  {
    "id": "bw4176",
    "contractNumber": "BW4176 768 A24",
    "projectCode": "BW4176",
    "fiscalYear": 2024,
    "contractor": "Dowd Roofing Inc",
    "contractorLocation": "Saint John NB",
    "trade": "Roofing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2024-05-27",
      "awarded": "2024-07-05",
      "startup": "2024-08-06",
      "substantial": "2024-12-13",
      "final": "2024-12-13"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Roof Replacement",
    "region": "New Brunswick",
    "scope": "Full roof system replacement on an occupied Government of New Brunswick facility — tear-off, insulation, membrane installation, and flashing details, coordinated to maintain building operations throughout.",
    "highlights": [
      "Late-season roofing execution — August startup carried to mid-December 2024 completion",
      "One of eight contracts managed with repeat roofing contractor Dowd Roofing Inc of Saint John"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/12-bridge-structure.jpg"
  },
  {
    "id": "bw4180",
    "contractNumber": "BW4180 SG8 A24",
    "projectCode": "BW4180",
    "fiscalYear": 2024,
    "contractor": "J E Wilson Roofing Co Ltd",
    "contractorLocation": "Saint John NB",
    "trade": "Roofing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2024-03-18",
      "awarded": "2024-04-24",
      "startup": "2024-05-13",
      "substantial": "2024-07-09",
      "final": "2024-07-09"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Roof Replacement",
    "region": "New Brunswick",
    "scope": "Full roof system replacement on an occupied Government of New Brunswick facility — tear-off, insulation, membrane installation, and flashing details, coordinated to maintain building operations throughout.",
    "highlights": [
      "Compressed eight-week roofing window — May 13 to July 9, 2024, substantial and final completion same day",
      "Open-tender award managed with J E Wilson Roofing of Saint John"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/10-architectural-detail.jpg"
  },
  {
    "id": "bw4h96",
    "contractNumber": "BW4H96 833 H02",
    "projectCode": "BW4H96",
    "fiscalYear": 2024,
    "contractor": "Dowd Roofing Inc",
    "contractorLocation": "Saint John NB",
    "trade": "Roofing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2024-11-22",
      "awarded": "2024-12-16",
      "startup": "2024-12-19",
      "substantial": "2025-03-28",
      "final": "2025-07-11"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Roof Replacement",
    "region": "New Brunswick",
    "scope": "Full roof system replacement on an occupied Government of New Brunswick facility — tear-off, insulation, membrane installation, and flashing details, coordinated to maintain building operations throughout.",
    "highlights": [
      "Winter roofing project — mobilized three days after a mid-December 2024 award, substantially complete by late March 2025",
      "One of eight contracts managed with repeat roofing contractor Dowd Roofing Inc of Saint John"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/12-bridge-structure.jpg"
  },
  {
    "id": "bw4p17",
    "contractNumber": "BW4P17 133 N03 -02",
    "projectCode": "BW4P17",
    "fiscalYear": 2024,
    "contractor": "Stor-It Systems Ltd",
    "contractorLocation": "Saint John NB",
    "trade": "Specialty & Civil",
    "tenderType": "Sole Source",
    "dates": {
      "tenderIssued": "2024-12-10",
      "awarded": "2024-12-13",
      "startup": "2025-01-08",
      "substantial": "2025-03-31",
      "final": "2025-05-31"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Specialty Works",
    "region": "New Brunswick",
    "scope": "Specialty construction package for a Government of New Brunswick site, managed from tender award through final completion.",
    "highlights": [
      "Sole-source specialty package awarded three days after tender issue (December 2024)",
      "Winter execution January–March 2025 to substantial completion"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/15-school-campus.jpg"
  },
  {
    "id": "bw4t12",
    "contractNumber": "BW4T12 V84 B5D",
    "projectCode": "BW4T12",
    "fiscalYear": 2024,
    "contractor": "NRB Construction Company Limited",
    "contractorLocation": "Saint John NB",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2024-02-23",
      "awarded": "2024-03-25",
      "startup": "2024-04-16",
      "substantial": "2024-07-23",
      "final": "2024-07-23"
    },
    "status": "Completed",
    "facilityName": "Renforth Maintenance Depot — Site Improvements",
    "region": "Renforth (Rothesay), New Brunswick",
    "scope": "Site improvements package at the provincial Renforth Maintenance Depot, publicly tendered as BW4T12 and managed from open tender award through same-day substantial and final completion.",
    "highlights": [
      "Publicly tendered on NBON/MERX as \"Site Improvements - Renforth Maintenance Depot - NB — BW4T12\"",
      "Fourteen-week execution — April 16 to July 23, 2024, substantial and final completion the same day"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/01-construction-site.jpg"
  },
  {
    "id": "bw4t18",
    "contractNumber": "BW4T18 00B 00B",
    "projectCode": "BW4T18",
    "fiscalYear": 2024,
    "contractor": "Avondale Construction Ltd",
    "contractorLocation": "Halifax NS",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2024-11-28",
      "awarded": "2025-02-21",
      "startup": "2025-03-11",
      "substantial": "2026-02-26",
      "final": ""
    },
    "status": "Completed",
    "facilityName": "New Upham Maintenance Depot & 5,000T Sand Arch",
    "region": "Upham, New Brunswick",
    "scope": "Construction of a new highway maintenance depot and 5,000-tonne sand storage arch for the Government of New Brunswick, managed from open tender through a full year of construction to substantial completion in February 2026.",
    "highlights": [
      "New-build depot plus 5,000T sand arch, publicly tendered on NBON (reference BW4T18) with closing extended to January 31, 2025",
      "Twelve-month construction duration — March 2025 startup to February 2026 substantial completion",
      "Interprovincial contractor coordination with Avondale Construction of Halifax, Nova Scotia"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/02-building-crane.jpg"
  },
  {
    "id": "bw4t25",
    "contractNumber": "BW4T25 VN1 B5D",
    "projectCode": "BW4T25",
    "fiscalYear": 2024,
    "contractor": "Mapleton Construction Ltd.",
    "contractorLocation": "Amherst NS",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-04-16",
      "awarded": "2025-05-20",
      "startup": "2025-05-23",
      "substantial": "2025-12-19",
      "final": "2026-01-22"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Renovation",
    "region": "New Brunswick",
    "scope": "General construction and interior renovation of a Government of New Brunswick facility, coordinating multiple sub-trades from tender through substantial completion.",
    "highlights": [
      "Seven-month execution from late-May 2025 startup to December 2025 substantial completion",
      "Interprovincial contractor coordination with Mapleton Construction of Amherst, Nova Scotia"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/05-concrete-building.jpg"
  },
  {
    "id": "bw3k13",
    "contractNumber": "BW3K13 Y96 B06",
    "projectCode": "BW3K13",
    "fiscalYear": 2023,
    "contractor": "Dowd Roofing Inc",
    "contractorLocation": "Saint John NB",
    "trade": "Roofing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2023-04-19",
      "awarded": "2023-05-16",
      "startup": "2023-06-01",
      "substantial": "2023-11-17",
      "final": "2023-11-17"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Roof Replacement",
    "region": "New Brunswick",
    "scope": "Full roof system replacement on an occupied Government of New Brunswick facility — tear-off, insulation, membrane installation, and flashing details, coordinated to maintain building operations throughout.",
    "highlights": [
      "One of eight contracts managed with repeat roofing contractor Dowd Roofing Inc of Saint John",
      "Full roofing season execution June–November 2023, with substantial and final completion achieved the same day"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/10-architectural-detail.jpg"
  },
  {
    "id": "bw3k25",
    "contractNumber": "BW3K25 Y90 B02",
    "projectCode": "BW3K25",
    "fiscalYear": 2023,
    "contractor": "John Flood & Sons (1961) Ltd",
    "contractorLocation": "SAINT JOHN NB",
    "trade": "Mechanical & Plumbing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-02-24",
      "awarded": "2025-04-02",
      "startup": "2025-04-17",
      "substantial": "2026-01-27",
      "final": "2026-04-14"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Mechanical Upgrade",
    "region": "New Brunswick",
    "scope": "Mechanical and plumbing systems upgrade in an operating government facility, including phased shutdowns and commissioning coordination.",
    "highlights": [
      "Year-long mechanical upgrade — April 2025 startup through substantial completion in January 2026 and final completion in April 2026",
      "One of three contracts managed with John Flood & Sons (1961) Ltd of Saint John"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/03-glass-tower.jpg"
  },
  {
    "id": "bw3t13",
    "contractNumber": "BW3T13 V74 B5D",
    "projectCode": "BW3T13",
    "fiscalYear": 2023,
    "contractor": "L Sanford & Sons Ltd",
    "contractorLocation": "Bloomfield Kings Co NB",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2024-04-19",
      "awarded": "2024-06-10",
      "startup": "2024-06-18",
      "substantial": "2024-10-21",
      "final": "2024-10-21"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Renovation",
    "region": "New Brunswick",
    "scope": "General construction and interior renovation of a Government of New Brunswick facility, coordinating multiple sub-trades from tender through substantial completion.",
    "highlights": [
      "Compressed summer-fall delivery — June to October 2024, with substantial and final completion the same day",
      "Open-tender award managed with L Sanford & Sons of Bloomfield, Kings County"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/17-construction-workers.jpg"
  },
  {
    "id": "bw3t25",
    "contractNumber": "BW3T25 V74 B5D",
    "projectCode": "BW3T25",
    "fiscalYear": 2023,
    "contractor": "Sussex Excavators (2010) Ltd",
    "contractorLocation": "Sussex NB",
    "trade": "Specialty & Civil",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2024-06-03",
      "awarded": "2024-07-11",
      "startup": "2024-07-22",
      "substantial": "2024-10-03",
      "final": "2024-10-03"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Specialty Works",
    "region": "New Brunswick",
    "scope": "Specialty construction package for a Government of New Brunswick site, managed from tender award through final completion.",
    "highlights": [
      "Civil/excavation specialty package executed July–October 2024, completed ahead of winter",
      "Delivered with Sussex Excavators (2010) Ltd following an open tender"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/20-recreation-center.jpg"
  },
  {
    "id": "by3943",
    "contractNumber": "BY3943 783 A24",
    "projectCode": "BY3943",
    "fiscalYear": 2023,
    "contractor": "John Flood & Sons (1961) Ltd",
    "contractorLocation": "SAINT JOHN NB",
    "trade": "Mechanical & Plumbing",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2023-04-20",
      "awarded": "2023-05-19",
      "startup": "2023-06-12",
      "substantial": "2024-02-29",
      "final": "2024-08-07"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Mechanical Upgrade",
    "region": "New Brunswick",
    "scope": "Mechanical and plumbing systems upgrade in an operating government facility, including phased shutdowns and commissioning coordination.",
    "highlights": [
      "Nine-month mechanical installation carried through the 2023–24 winter to substantial completion in February 2024",
      "One of three contracts managed with John Flood & Sons (1961) Ltd of Saint John"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/13-warehouse-industrial.jpg"
  },
  {
    "id": "by3k39",
    "contractNumber": "BY3K39 126 B02",
    "projectCode": "BY3K39",
    "fiscalYear": 2023,
    "contractor": "Gerry's Welding & Fabrication Inc.",
    "contractorLocation": "Saint John NB",
    "trade": "Specialty & Civil",
    "tenderType": "Sole Source",
    "dates": {
      "tenderIssued": "2023-09-26",
      "awarded": "2023-09-28",
      "startup": "2023-10-25",
      "substantial": "2024-01-09",
      "final": "2024-01-26"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Specialty Works",
    "region": "New Brunswick",
    "scope": "Specialty construction package for a Government of New Brunswick site, managed from tender award through final completion.",
    "highlights": [
      "Urgent sole-source award — contract awarded two days after tender issue (Sept 26–28, 2023)",
      "First of two successive sole-source packages managed on project BY3K39",
      "Executed through winter to January 2024 completion"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/15-school-campus.jpg"
  },
  {
    "id": "by3k39-02",
    "contractNumber": "BY3K39 126 B02 -02",
    "projectCode": "BY3K39",
    "fiscalYear": 2023,
    "contractor": "Integrated HVAC Solutions",
    "contractorLocation": "Summerville NB",
    "trade": "HVAC & Ventilation",
    "tenderType": "Sole Source",
    "dates": {
      "tenderIssued": "2023-11-17",
      "awarded": "2023-11-19",
      "startup": "2023-11-20",
      "substantial": "2024-04-08",
      "final": ""
    },
    "status": "Completed",
    "facilityName": "Provincial Facility HVAC Upgrade",
    "region": "New Brunswick",
    "scope": "Ventilation and HVAC system replacement for a Government of New Brunswick building, including equipment procurement lead-time management and seasonal changeover planning.",
    "highlights": [
      "Emergency-pace sole-source award — contractor mobilized one day after award (Nov 19–20, 2023)",
      "Second package managed on project BY3K39, delivered through winter to April 2024 substantial completion"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/03-glass-tower.jpg"
  },
  {
    "id": "by3k40",
    "contractNumber": "BY3K40 147 B02",
    "projectCode": "BY3K40",
    "fiscalYear": 2023,
    "contractor": "Dexter Construction Company Ltd",
    "contractorLocation": "Bedford NS",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2024-03-11",
      "awarded": "2024-04-11",
      "startup": "2024-04-19",
      "substantial": "2024-06-25",
      "final": "2024-06-25"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Renovation",
    "region": "New Brunswick",
    "scope": "General construction and interior renovation of a Government of New Brunswick facility, coordinating multiple sub-trades from tender through substantial completion.",
    "highlights": [
      "Fast-track ten-week execution — April 19 to June 25, 2024, substantial and final completion same day",
      "Interprovincial contractor coordination with Dexter Construction of Bedford, Nova Scotia"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/01-construction-site.jpg"
  },
  {
    "id": "by3k41",
    "contractNumber": "BY3K41 126 B02",
    "projectCode": "BY3K41",
    "fiscalYear": 2023,
    "contractor": "Atlantic Alarm & Sound Ltd",
    "contractorLocation": "Moncton NB",
    "trade": "Electrical & Security",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2023-10-27",
      "awarded": "2023-12-04",
      "startup": "2023-12-15",
      "substantial": "2024-06-13",
      "final": "2024-10-09"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Systems Upgrade",
    "region": "New Brunswick",
    "scope": "Electrical, fire-alarm, and security systems installation in an occupied government facility, coordinated around daily operations.",
    "highlights": [
      "Winter award (December 2023) with installation carried through to June 2024 substantial completion",
      "Repeat contractor relationship — Atlantic Alarm & Sound also delivered a later managed contract (BW5K18)"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/09-office-interior.jpg"
  },
  {
    "id": "by3k42",
    "contractNumber": "BY3K42 Y90 B02",
    "projectCode": "BY3K42",
    "fiscalYear": 2023,
    "contractor": "Eclipse Construction Services Ltd",
    "contractorLocation": "Rothesay NB",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2023-04-12",
      "awarded": "2023-05-17",
      "startup": "2023-05-25",
      "substantial": "2024-06-06",
      "final": "2024-11-13"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Renovation",
    "region": "New Brunswick",
    "scope": "General construction and interior renovation of a Government of New Brunswick facility, coordinating multiple sub-trades from tender through substantial completion.",
    "highlights": [
      "Year-long general construction contract — May 2023 startup to June 2024 substantial completion",
      "Repeat contractor relationship — Eclipse Construction Services appears on four managed contracts"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/02-building-crane.jpg"
  },
  {
    "id": "by3t79",
    "contractNumber": "BY3T79 V84 B5D -02",
    "projectCode": "BY3T79",
    "fiscalYear": 2023,
    "contractor": "Valley Refrigeration & Air Conditioning Ltd",
    "contractorLocation": "Jacksonville NB",
    "trade": "HVAC & Ventilation",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2023-11-06",
      "awarded": "2024-01-16",
      "startup": "2024-01-24",
      "substantial": "2024-12-20",
      "final": "2025-01-23"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility HVAC Upgrade",
    "region": "New Brunswick",
    "scope": "Ventilation and HVAC system replacement for a Government of New Brunswick building, including equipment procurement lead-time management and seasonal changeover planning.",
    "highlights": [
      "Mid-winter award (January 2024) with contractor startup within eight days",
      "Eleven-month HVAC replacement carried to substantial completion in December 2024"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/13-warehouse-industrial.jpg"
  },
  {
    "id": "by2r20",
    "contractNumber": "BY2R20 SL1 TP1",
    "projectCode": "BY2R20",
    "fiscalYear": 2022,
    "contractor": "Kathron Construction Ltd",
    "contractorLocation": "St Martins NB",
    "trade": "General Construction",
    "tenderType": "Invited",
    "dates": {
      "tenderIssued": "2023-10-24",
      "awarded": "2023-11-06",
      "startup": "2023-11-09",
      "substantial": "2023-12-05",
      "final": "2023-12-05"
    },
    "status": "Completed",
    "facilityName": "West Reception Centre — Fundy Trail Parkway",
    "region": "Bay View, Saint John County, New Brunswick",
    "scope": "General construction package at the West Reception Centre of Fundy Trail Provincial Park, managed as the first of three successive contracts on this facility, from invited tender through substantial completion.",
    "highlights": [
      "First of three successive contracts (2023–2025) managed on the same Fundy Trail Parkway reception centre project",
      "Invited tender taken from startup to substantial completion in under one month (Nov 9 – Dec 5, 2023)",
      "Delivered with Kathron Construction of St Martins, local to the parkway's west entrance"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/05-concrete-building.jpg"
  },
  {
    "id": "by2r20-02",
    "contractNumber": "BY2R20 SL1 TP1 -02",
    "projectCode": "BY2R20",
    "fiscalYear": 2022,
    "contractor": "E R Steeves Ltd",
    "contractorLocation": "Quispamsis NB",
    "trade": "General Construction",
    "tenderType": "Invited",
    "dates": {
      "tenderIssued": "2024-04-24",
      "awarded": "2024-05-15",
      "startup": "2024-05-23",
      "substantial": "2024-05-31",
      "final": "2024-05-31"
    },
    "status": "Completed",
    "facilityName": "West Reception Centre — Fundy Trail Parkway",
    "region": "Bay View, Saint John County, New Brunswick",
    "scope": "Second general construction package at the West Reception Centre of Fundy Trail Provincial Park, managed under the same parent project from invited tender through completion.",
    "highlights": [
      "Second of three phased contracts managed on the Fundy Trail Parkway reception centre (2023–2025)",
      "Rapid execution — startup to substantial and final completion within nine days (May 23–31, 2024)"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/17-construction-workers.jpg"
  },
  {
    "id": "by2r20-03",
    "contractNumber": "BY2R20 SL1 TP1 -03",
    "projectCode": "BY2R20",
    "fiscalYear": 2022,
    "contractor": "Eclipse Construction Services Ltd",
    "contractorLocation": "Rothesay NB",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-01-21",
      "awarded": "2025-03-12",
      "startup": "2025-03-27",
      "substantial": "",
      "final": ""
    },
    "status": "Active",
    "facilityName": "West Reception Centre — Fundy Trail Parkway",
    "region": "Bay View, Saint John County, New Brunswick",
    "scope": "Third general construction package at the West Reception Centre of Fundy Trail Provincial Park, publicly tendered as BY2R20-03 and managed from open tender award through active construction.",
    "highlights": [
      "Publicly tendered on NBON/MERX as \"West Reception Centre - Fundy Trail Parkway, NB — BY2R20-03\"",
      "Final phase of a three-contract project run successively from 2023 to 2025",
      "Repeat contractor relationship — Eclipse Construction Services appears on four managed contracts"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/01-construction-site.jpg"
  },
  {
    "id": "by2r28",
    "contractNumber": "BY2R28 SK9 TP1",
    "projectCode": "BY2R28",
    "fiscalYear": 2022,
    "contractor": "Vertex Solar Solutions Inc",
    "contractorLocation": "Shediac River NB",
    "trade": "Specialty & Civil",
    "tenderType": "Invited",
    "dates": {
      "tenderIssued": "2023-08-16",
      "awarded": "2023-09-01",
      "startup": "2023-09-28",
      "substantial": "2023-12-01",
      "final": "2024-06-18"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Specialty Works",
    "region": "New Brunswick",
    "scope": "Specialty construction package for a Government of New Brunswick site, managed from tender award through final completion.",
    "highlights": [
      "Invited tender awarded September 2023 and carried to substantial completion by December 2023, ahead of winter",
      "Specialty package delivered with a solar-energy contractor, Vertex Solar Solutions of Shediac River NB"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/20-recreation-center.jpg"
  },
  {
    "id": "by479a",
    "contractNumber": "BY479A VG4 B5D",
    "projectCode": "BY479A",
    "fiscalYear": 2022,
    "contractor": "Maxim Construction Inc",
    "contractorLocation": "Saint John NB",
    "trade": "General Construction",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2026-01-13",
      "awarded": "2026-03-10",
      "startup": "2026-03-26",
      "substantial": "",
      "final": ""
    },
    "status": "Active",
    "facilityName": "Provincial Facility Renovation",
    "region": "New Brunswick",
    "scope": "General construction and interior renovation of a Government of New Brunswick facility, coordinating multiple sub-trades from tender through substantial completion.",
    "highlights": [
      "One of two related contracts managed under parent project BY479A, alongside a specialty package (BY479B)",
      "Awarded March 2026 following an open tender; currently in active construction"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/02-building-crane.jpg"
  },
  {
    "id": "by479b",
    "contractNumber": "BY479B VG4 B5D",
    "projectCode": "BY479B",
    "fiscalYear": 2022,
    "contractor": "Coastal Enterprises",
    "contractorLocation": "Lepreau NB",
    "trade": "Specialty & Civil",
    "tenderType": "Open",
    "dates": {
      "tenderIssued": "2025-04-11",
      "awarded": "2025-05-28",
      "startup": "2025-06-11",
      "substantial": "2025-09-19",
      "final": "2025-12-04"
    },
    "status": "Completed",
    "facilityName": "Provincial Facility Specialty Works",
    "region": "New Brunswick",
    "scope": "Specialty construction package for a Government of New Brunswick site, managed from tender award through final completion.",
    "highlights": [
      "Companion specialty package to general construction contract BY479A under the same parent project",
      "Delivered with Coastal Enterprises of Lepreau, on New Brunswick's Bay of Fundy coast",
      "Summer-fall execution June–September 2025 with final completion in December 2025"
    ],
    "images": [],
    "thumbnail": "/portfolio/images/15-school-campus.jpg"
  }
];
