export interface PortfolioProject {
  id: string;
  title: string;
  category: string;
  location: string;
  projectType: string;
  thumbnail: string;
  images: string[];
  description: string;
  scope: string;
  servicesProvided: string[];
  deliverables: string[];
  projectValue?: string;
  year?: string;
}

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    id: "proj-01", title: "Mixed-Use Tower Complex", category: "Estimation",
    location: "Toronto, ON", projectType: "Mixed-Use",
    thumbnail: "/portfolio/images/01-construction-site.jpg", images: [],
    description: "Detailed cost estimation for a 42-story mixed-use tower with retail, office, and residential components. Full quantity takeoff across 12 trades with AACE Class 2 accuracy.",
    scope: "Full QTO and detailed estimate for architectural, structural, MEP, and interior trades.",
    servicesProvided: ["EST-03", "EST-06", "EST-07"],
    deliverables: ["Detailed Estimate Report", "Multi-Trade QTO", "Bill of Quantities"],
    projectValue: "$50M+", year: "2025",
  },
  {
    id: "proj-02", title: "Healthcare Facility Expansion", category: "Scheduling",
    location: "Vancouver, BC", projectType: "Healthcare",
    thumbnail: "/portfolio/images/02-building-crane.jpg", images: [],
    description: "Baseline CPM schedule and monthly updates for a 120-bed hospital expansion. Critical path analysis across 8 phases with resource-loaded activities.",
    scope: "Baseline schedule development, monthly progress updates, and delay analysis.",
    servicesProvided: ["SCH-01", "SCH-02", "SCH-03"],
    deliverables: ["Baseline CPM Schedule", "Monthly Update Reports", "Schedule Health Audit"],
    projectValue: "$10M – $50M", year: "2025",
  },
  {
    id: "proj-03", title: "Commercial Office Retrofit", category: "Project Controls",
    location: "Calgary, AB", projectType: "Commercial",
    thumbnail: "/portfolio/images/03-glass-tower.jpg", images: [],
    description: "Monthly retainer for project controls on a Class A office building retrofit. Cash flow projections, S-curve tracking, and earned value analysis.",
    scope: "Ongoing project controls and cost monitoring for 18-month retrofit program.",
    servicesProvided: ["CTL-02", "CTL-03"],
    deliverables: ["Monthly Controls Report", "Cash Flow Projection", "S-Curve Analysis"],
    projectValue: "$5M – $10M", year: "2024",
  },
  {
    id: "proj-04", title: "Luxury Residential Compound", category: "Estimation",
    location: "Dubai, UAE", projectType: "Residential",
    thumbnail: "/portfolio/images/04-architecture-modern.jpg", images: [],
    description: "Conceptual cost estimate for a luxury residential compound — 24 villas with shared amenities. AACE Class 5/4 estimate for feasibility assessment.",
    scope: "Conceptual estimate based on schematic design drawings and area programs.",
    servicesProvided: ["EST-01", "EST-05"],
    deliverables: ["Conceptual Estimate", "Cost per SF Analysis"],
    projectValue: "$10M – $50M", year: "2025",
  },
  {
    id: "proj-05", title: "University Campus Redevelopment", category: "Design Management",
    location: "Edmonton, AB", projectType: "Institutional",
    thumbnail: "/portfolio/images/05-concrete-building.jpg", images: [],
    description: "Design management retainer for a university campus redevelopment. RFI management, submittal tracking, and consultant coordination across 6 disciplines.",
    scope: "Design phase coordination, RFI/submittal management, and budget assessment.",
    servicesProvided: ["DMR-01"],
    deliverables: ["RFI Log & Responses", "Submittal Register", "Design Phase Budget Report"],
    projectValue: "$50M+", year: "2024",
  },
  {
    id: "proj-06", title: "Industrial Distribution Center", category: "Estimation",
    location: "Mississauga, ON", projectType: "Industrial",
    thumbnail: "/portfolio/images/06-apartment-facade.jpg", images: [],
    description: "Bid-ready estimate for a 250,000 SF warehouse distribution center. AACE Class 1 accuracy with full trade breakdowns for competitive bidding.",
    scope: "Complete bid-ready estimate from 100% construction documents.",
    servicesProvided: ["EST-04", "EST-06", "EST-07"],
    deliverables: ["Bid-Ready Estimate", "Multi-Trade QTO", "Bill of Quantities"],
    projectValue: "$10M – $50M", year: "2025",
  },
  {
    id: "proj-07", title: "Hotel Renovation Recovery", category: "Scheduling",
    location: "Niagara Falls, ON", projectType: "Hospitality",
    thumbnail: "/portfolio/images/07-residential-project.jpg", images: [],
    description: "Schedule recovery plan for a delayed 200-room hotel renovation. Forensic delay analysis followed by accelerated recovery schedule.",
    scope: "Forensic schedule analysis, recovery plan, and weekly progress monitoring.",
    servicesProvided: ["SCH-04", "SCH-05"],
    deliverables: ["Forensic Delay Report", "Recovery Schedule", "Weekly Dashboard"],
    projectValue: "$5M – $10M", year: "2024",
  },
  {
    id: "proj-08", title: "Data Center MEP Evaluation", category: "Evaluation & Advisory",
    location: "Ashburn, VA", projectType: "Data Center",
    thumbnail: "/portfolio/images/08-hospital-building.jpg", images: [],
    description: "Constructability review and cost evaluation for a Tier III data center. Focus on MEP systems, redundancy requirements, and contractor qualification.",
    scope: "Pre-construction evaluation covering cost, constructability, and contractor readiness.",
    servicesProvided: ["EVL-01", "EVL-02", "EVL-04"],
    deliverables: ["Cost Evaluation Report", "Contractor Scorecard", "Constructability Memo"],
    projectValue: "$10M – $50M", year: "2025",
  },
  {
    id: "proj-09", title: "Corporate Fit-Out QA Program", category: "Quality Assurance",
    location: "Bangalore, India", projectType: "Interior Fit-out",
    thumbnail: "/portfolio/images/09-office-interior.jpg", images: [],
    description: "QA/QC plan development and inspection checklists for a 45,000 SF corporate office fit-out. Trade-specific quality standards.",
    scope: "Quality program development, inspection protocols, and checklist packages.",
    servicesProvided: ["QAP-01", "QAP-02"],
    deliverables: ["QA/QC Plan Document", "Inspection Checklist Package"],
    projectValue: "$1M – $5M", year: "2025",
  },
  {
    id: "proj-10", title: "Heritage Renovation Analysis", category: "Estimation",
    location: "Ottawa, ON", projectType: "Renovation",
    thumbnail: "/portfolio/images/10-architectural-detail.jpg", images: [],
    description: "Change order estimation for a heritage building renovation. Independent cost analysis for 14 change orders totaling $1.2M in scope additions.",
    scope: "Independent review of contractor-submitted change orders.",
    servicesProvided: ["EST-08", "EVL-01"],
    deliverables: ["Change Order Analysis Report", "Fair Cost Assessment"],
    projectValue: "$1M – $5M", year: "2024",
  },
  {
    id: "proj-11", title: "Retail Plaza Estimate", category: "Estimation",
    location: "Brampton, ON", projectType: "Commercial",
    thumbnail: "/portfolio/images/11-white-building.jpg", images: [],
    description: "Progressive cost estimation for a 180,000 SF retail plaza with anchor tenant fit-outs and shared parking structure.",
    scope: "Progressive estimation from AACE Class 5 through Class 2.",
    servicesProvided: ["EST-01", "EST-02", "EST-03"],
    deliverables: ["Conceptual Estimate", "DD Estimate", "Detailed Estimate"],
    projectValue: "$10M – $50M", year: "2025",
  },
  {
    id: "proj-12", title: "Transit Station Schedule", category: "Scheduling",
    location: "Montreal, QC", projectType: "Institutional",
    thumbnail: "/portfolio/images/12-bridge-structure.jpg", images: [],
    description: "Baseline CPM schedule for a new light rail transit station with underground utilities and elevated platform construction.",
    scope: "Resource-loaded baseline schedule with critical path analysis.",
    servicesProvided: ["SCH-01", "SCH-02"],
    deliverables: ["Baseline CPM Schedule", "Monthly Updates"],
    projectValue: "$50M+", year: "2025",
  },
  {
    id: "proj-13", title: "Warehouse Expansion Controls", category: "Project Controls",
    location: "Peel Region, ON", projectType: "Industrial",
    thumbnail: "/portfolio/images/13-warehouse-industrial.jpg", images: [],
    description: "Fractional project controls for a phased warehouse expansion. Earned value tracking and cash flow projections.",
    scope: "Monthly controls reporting, S-curve analysis, and milestone tracking.",
    servicesProvided: ["CTL-01", "CTL-03"],
    deliverables: ["Monthly Dashboard", "Cash Flow Forecast", "S-Curve Report"],
    projectValue: "$5M – $10M", year: "2024",
  },
  {
    id: "proj-14", title: "Boutique Hotel Design Mgmt", category: "Design Management",
    location: "Victoria, BC", projectType: "Hospitality",
    thumbnail: "/portfolio/images/14-hotel-luxury.jpg", images: [],
    description: "Design management retainer for a boutique hotel renovation. Submittal tracking, RFI management, consultant coordination.",
    scope: "Full design phase coordination and document control.",
    servicesProvided: ["DMR-01"],
    deliverables: ["RFI Log", "Submittal Register", "Coordination Report"],
    projectValue: "$5M – $10M", year: "2025",
  },
  {
    id: "proj-15", title: "School Addition Bid Estimate", category: "Estimation",
    location: "Winnipeg, MB", projectType: "Institutional",
    thumbnail: "/portfolio/images/15-school-campus.jpg", images: [],
    description: "Bid-ready estimate for a 40,000 SF elementary school addition with gymnasium, classrooms, and mechanical upgrades.",
    scope: "Complete Class 1 estimate from 100% construction documents.",
    servicesProvided: ["EST-04", "EST-05", "EST-07"],
    deliverables: ["Bid-Ready Estimate", "QTO", "Bill of Quantities"],
    projectValue: "$5M – $10M", year: "2025",
  },
  {
    id: "proj-16", title: "Condo Tower Delay Analysis", category: "Scheduling",
    location: "Surrey, BC", projectType: "Residential",
    thumbnail: "/portfolio/images/16-residential-luxury.jpg", images: [],
    description: "Schedule health audit and forensic delay analysis for a 35-story residential tower experiencing 4-month delays.",
    scope: "Independent schedule review, delay cause analysis, recovery plan.",
    servicesProvided: ["SCH-03", "SCH-05"],
    deliverables: ["Schedule Audit Report", "Forensic Delay Analysis"],
    projectValue: "$10M – $50M", year: "2024",
  },
  {
    id: "proj-17", title: "Office Contractor Evaluation", category: "Evaluation & Advisory",
    location: "Markham, ON", projectType: "Commercial",
    thumbnail: "/portfolio/images/17-construction-workers.jpg", images: [],
    description: "Pre-qualification evaluation of 6 general contractors for a Class A office development.",
    scope: "Contractor evaluation, scoring, and recommendation report.",
    servicesProvided: ["EVL-02", "EVL-03"],
    deliverables: ["Evaluation Matrix", "Performance Assessment"],
    projectValue: "$10M – $50M", year: "2025",
  },
  {
    id: "proj-18", title: "Medical Clinic QA Program", category: "Quality Assurance",
    location: "Halifax, NS", projectType: "Healthcare",
    thumbnail: "/portfolio/images/18-medical-facility.jpg", images: [],
    description: "QA/QC plan and inspection checklists for a specialty medical clinic with infection control and HVAC commissioning protocols.",
    scope: "Healthcare-specific quality program with regulatory compliance.",
    servicesProvided: ["QAP-01", "QAP-02"],
    deliverables: ["Healthcare QA/QC Plan", "Inspection Checklists"],
    projectValue: "$1M – $5M", year: "2025",
  },
  {
    id: "proj-19", title: "Mixed-Use Cash Flow Analysis", category: "Project Controls",
    location: "London, ON", projectType: "Mixed-Use",
    thumbnail: "/portfolio/images/19-city-skyline.jpg", images: [],
    description: "Cash flow projection and S-curve analysis for a 24-month mixed-use development aligned with lender requirements.",
    scope: "Financial controls and cash flow forecasting.",
    servicesProvided: ["CTL-02", "CTL-03"],
    deliverables: ["Monthly Cash Flow Report", "S-Curve", "Draw Schedule"],
    projectValue: "$10M – $50M", year: "2024",
  },
  {
    id: "proj-20", title: "Recreation Center Estimate", category: "Estimation",
    location: "Kelowna, BC", projectType: "Institutional",
    thumbnail: "/portfolio/images/20-recreation-center.jpg", images: [],
    description: "Design development estimate for a community recreation center with aquatic facility and multi-purpose courts.",
    scope: "DD-level estimate with trade breakdowns and benchmarking.",
    servicesProvided: ["EST-02", "EST-06"],
    deliverables: ["DD Estimate Report", "Multi-Trade QTO"],
    projectValue: "$10M – $50M", year: "2025",
  },
  {
    id: "proj-21", title: "Project Coordination Meeting", category: "Design Management",
    location: "Toronto, ON", projectType: "Commercial",
    thumbnail: "/portfolio/images/21-team-meeting.jpg", images: [],
    description: "Design coordination and consultant management for a multi-phase commercial development.",
    scope: "Cross-discipline coordination, design review sessions.",
    servicesProvided: ["DMR-01"],
    deliverables: ["Coordination Minutes", "Design Review Report"],
    projectValue: "$10M – $50M", year: "2025",
  },
  {
    id: "proj-22", title: "Modern Residence Estimate", category: "Estimation",
    location: "West Vancouver, BC", projectType: "Residential",
    thumbnail: "/portfolio/images/22-modern-house.jpg", images: [],
    description: "Detailed estimate for a contemporary single-family residence with smart home systems and sustainable design.",
    scope: "Full residential estimate with specialty trade breakdowns.",
    servicesProvided: ["EST-03", "EST-05"],
    deliverables: ["Detailed Estimate", "Single-Trade QTO"],
    projectValue: "$1M – $5M", year: "2025",
  },
  {
    id: "proj-23", title: "Data Center Cost Evaluation", category: "Evaluation & Advisory",
    location: "Montreal, QC", projectType: "Data Center",
    thumbnail: "/portfolio/images/23-data-center.jpg", images: [],
    description: "Cost evaluation and constructability review for a Tier III data center with redundancy analysis.",
    scope: "Pre-construction cost and feasibility assessment.",
    servicesProvided: ["EVL-01", "EVL-04"],
    deliverables: ["Cost Evaluation", "Constructability Review"],
    projectValue: "$50M+", year: "2025",
  },
  {
    id: "proj-24", title: "Highrise Schedule Baseline", category: "Scheduling",
    location: "Burnaby, BC", projectType: "Residential",
    thumbnail: "/portfolio/images/24-highrise-construction.jpg", images: [],
    description: "Baseline CPM schedule for a 48-story residential tower with podium parking and amenity levels.",
    scope: "Resource-loaded baseline with milestone tracking.",
    servicesProvided: ["SCH-01", "SCH-02"],
    deliverables: ["Baseline Schedule", "Monthly Progress Reports"],
    projectValue: "$50M+", year: "2024",
  },
  {
    id: "proj-25", title: "Site Planning QA Review", category: "Quality Assurance",
    location: "Regina, SK", projectType: "Institutional",
    thumbnail: "/portfolio/images/25-blueprint-plan.jpg", images: [],
    description: "QA/QC plan for a municipal site development with grading, drainage, and utility coordination.",
    scope: "Site-specific quality protocols and inspection planning.",
    servicesProvided: ["QAP-01"],
    deliverables: ["QA/QC Plan", "Site Inspection Protocol"],
    projectValue: "$1M – $5M", year: "2025",
  },
  {
    id: "proj-26", title: "Interior Design Controls", category: "Project Controls",
    location: "Oakville, ON", projectType: "Interior Fit-out",
    thumbnail: "/portfolio/images/26-interior-design.jpg", images: [],
    description: "Monthly controls retainer for a high-end commercial interior fit-out project.",
    scope: "Cost tracking, change management, and schedule monitoring.",
    servicesProvided: ["CTL-02"],
    deliverables: ["Monthly Controls Report", "Change Order Log"],
    projectValue: "$1M – $5M", year: "2024",
  },
  {
    id: "proj-27", title: "Commercial Tower Estimate", category: "Estimation",
    location: "Vaughan, ON", projectType: "Commercial",
    thumbnail: "/portfolio/images/27-commercial-building.jpg", images: [],
    description: "Design development estimate for a 12-story commercial office tower with ground-floor retail.",
    scope: "DD-level estimate with full trade breakdown.",
    servicesProvided: ["EST-02", "EST-06", "EST-07"],
    deliverables: ["DD Estimate", "Multi-Trade QTO", "BOQ"],
    projectValue: "$10M – $50M", year: "2025",
  },
  {
    id: "proj-28", title: "Renovation Scope Analysis", category: "Evaluation & Advisory",
    location: "Kingston, ON", projectType: "Renovation",
    thumbnail: "/portfolio/images/28-renovation-work.jpg", images: [],
    description: "Scope evaluation and performance assessment for a multi-phase heritage renovation project.",
    scope: "Independent scope review and contractor performance evaluation.",
    servicesProvided: ["EVL-01", "EVL-03"],
    deliverables: ["Scope Analysis Report", "Performance Assessment"],
    projectValue: "$5M – $10M", year: "2024",
  },
  {
    id: "proj-29", title: "Site Development Schedule", category: "Scheduling",
    location: "Saskatoon, SK", projectType: "Institutional",
    thumbnail: "/portfolio/images/29-site-planning.jpg", images: [],
    description: "Baseline schedule and monthly updates for a municipal recreation site development with phased construction.",
    scope: "Phased schedule coordination with utility and grading sequences.",
    servicesProvided: ["SCH-01", "SCH-02", "SCH-03"],
    deliverables: ["Baseline Schedule", "Monthly Updates", "Health Audit"],
    projectValue: "$5M – $10M", year: "2025",
  },
  {
    id: "proj-30", title: "Mixed-Use Bid Package", category: "Estimation",
    location: "Hamilton, ON", projectType: "Mixed-Use",
    thumbnail: "/portfolio/images/30-mixed-use-building.jpg", images: [],
    description: "Bid-ready estimate for a 6-story mixed-use development with residential units above commercial ground floor.",
    scope: "Full bid package with competitive pricing breakdown.",
    servicesProvided: ["EST-04", "EST-06", "EST-07"],
    deliverables: ["Bid-Ready Estimate", "QTO Package", "BOQ"],
    projectValue: "$10M – $50M", year: "2025",
  },
];

export const CATEGORY_COLORS: Record<string, string> = {
  Estimation: "#B8922E",
  Scheduling: "#4A90D9",
  "Project Controls": "#E67E22",
  "Design Management": "#8E44AD",
  "Evaluation & Advisory": "#27AE60",
  "Quality Assurance": "#C0392B",
};
